graph LR
  I0["document_classifier.py"]
  I1["entity_linker.py"]
  I2["metadata_parser.py"]
  I3["ocr_gui.py"]
  I4["ocr_worker.py"]
  I5["zone_extractor.py"]
  I6["validate_data.py"]
  I7["all_collections_summary.py"]
  I8["church_committee_test.py"]
  I9["citation_generator.py"]
  I10["classifier_feedback_test.py"]
  I11["classifier_test.py"]
  I12["classifier_test_html.py"]
  I13["clean_baseline.py"]
  I14["create_test_pdf.py"]
  I15["deduplicate_baseline.py"]
  I16["discover_patterns.py"]
  I17["entity_matcher.py"]
  I18["full_pipeline_test.py"]
  I19["inflation.py"]
  I20["merge_data.py"]
  I21["ocr_server.py"]
  I22["prove_it_works.py"]
  I23["restructure_events.py"]
  I24["scan_pdf.py"]
  I25["tag_yates_entities.py"]
  I26["test_classifier.py"]
  I27["train_classifier.py"]
  I28["wc_volume_test.py"]
  I29["yates_test.py"]
